version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    networks:
      - proxy
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
     
networks:
  proxy:
    external: true
     
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw,nfsvers=4,async"
      device: ":/volume1/docker/proxy/data"
  letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw,nfsvers=4,async"
      device: ":/volume1/docker/proxy/letsencrypt"
