version: "3.7"

services:
  caddy:
    image: awesome/webapp
    build: .
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - data:/data
      - config:/config
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/docker/caddy/data"
  config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/docker/caddy/config"
