version: "3.7"

services:
  caddy:
    build: ./
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  caddy_data:
    external: true
    driver_opts:
    type: "nfs"
    o: "addr=192.168.1.10,nolock,soft,rw,nfsvers=4,async"
    device: ":/volume1/docker/caddy
  
  caddy_config:
