version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    #command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      #- "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=false"
      #- "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
      #- "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_API_KEY=${CF_API_KEY}"
    volumes:
      - "letsencrypt:/letsencrypt"
      - ./config.yml:/config.yml:ro
      - ./traefik.yml:/traefik.yml:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - shared

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.felines.space`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/docker/traefik"
