global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"    
    http:
      middlewares:
        - https-redirect
  websecure:
    address: ":443"

providers:
  # --- Docker Provider
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # --- File Provider for external services
  file:
    filename: /config.yml

# --- DNS Challenge on Cloudflare
certificatesResolvers:
  myresolver:
    acme:
      email: mail@felines.space
      storage: acme.json
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 0
