---
version: "2.1"
services:
  app:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
      - TZ=Europe/Rome
    volumes:
      - config:/config
    ports:
      - 8888:80
      #- 443:443 #optional
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/docker/dokuwiki"
