---
version: "3.9"
services:
  app:
    image: lscr.io/linuxserver/dokuwiki:latest
    restart: unless-stopped
    container_name: dokuwiki
    environment:
      - TZ=Europe/Rome
    volumes:
      - config:/config
    ports:
      - "8888:80"
      #- 443:443 #optional

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/docker/dokuwiki"
